### PR TITLE
Fixing escape issues with curl and zsh

### PR DESCRIPTION
**Pull request by danielmapar**
Issue [here](https://github.com/ServiceWeaver/website/issues/2)

### CODE REVIEW

**Comment by mwhittaker** [comment]
Hi @danielmapar! Thanks so much for this fix. Do you mind re-opening your pull request on the [main Service Weaver repo](https://github.com/serviceweaver/weaver)? Look at the [`website` directory](https://github.com/ServiceWeaver/weaver/tree/main/website) in particular. This repo contains the generated website, but the `website` directory in the main repo contains the website's source code. Very soon, we'll be deleting this repo entirely and serving everything from the main `weaver` repo.

**Comment by danielmapar** [comment]
No problem @mwhittaker. [Here](https://github.com/ServiceWeaver/weaver/pull/121) is the new PR in the weaver repo.

**Comment by mwhittaker** [comment]
Thanks so much @danielmapar! Really appreciate it.

**Comment by danielmapar** [comment]
No problem at all, will close this for now.

**Pull request closed without merging**
